import { Young_Serif, Newsreader, Karla } from 'next/font/google';
import { AuthProvider } from '@/lib/auth-context';
import './global.css';

const youngSerif = Young_Serif({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-heading',
});

const newsreader = Newsreader({
  subsets: ['latin'],
  variable: '--font-body',
});

const karla = Karla({
  subsets: ['latin'],
  variable: '--font-label',
});

export const metadata = {
  title: 'Plot-Twist',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${youngSerif.variable} ${newsreader.variable} ${karla.variable}`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
